"""
add approvals table

Revision ID: 0001_approvals
Revises:
Create Date: 2026-07-12

The first real table (replaces the ExampleRecord scaffold, which was never
migrated). Hand-written rather than autogenerated so it does not require a
live database to produce. Mirrors data.models.ApprovalRecord.
"""

import sqlalchemy as sa
from alembic import op


revision = "0001_approvals"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "approvals",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("requester_id", sa.String(), nullable=False),
        sa.Column("origin", sa.Text(), nullable=False),
        sa.Column("request_text", sa.Text(), nullable=False),
        sa.Column("tool_name", sa.String(), nullable=False),
        sa.Column("tool_arguments", sa.Text(), nullable=False),
        sa.Column("run_state_json", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("card_channel", sa.String(), nullable=False),
        sa.Column("card_ts", sa.String(), nullable=False),
        sa.Column("resolver_id", sa.String(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_approvals_status", "approvals", ["status"])


def downgrade() -> None:
    op.drop_index("ix_approvals_status", table_name="approvals")
    op.drop_table("approvals")
